# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a594669f16640ace0ef25867db5b5fb1a31b80944446b7d4e4e930a485ec7a97f5c5d10e3537dd25deaa1761cc3813b843570ace07b52842037516136b814736

test:
  secret_key_base: 39a9cf9b561f8ef25833688444cd17cebd841cf9e0bfe325de4b790e5976d112b6724b999127036a93c240065da410362eb211008b087c038583d240e4cc396a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
